package com.tyq.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COLLECT.
 */
public class Collect {

    private Long id;
    private String title;
    private String imageUrl;
    private String url;
    private java.util.Date time;

    public Collect() {
    }

    public Collect(Long id) {
        this.id = id;
    }

    public Collect(Long id, String title, String imageUrl, String url, java.util.Date time) {
        this.id = id;
        this.title = title;
        this.imageUrl = imageUrl;
        this.url = url;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

}
