package com.tyq.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tyq.greendao.HaveRead;
import com.tyq.greendao.Collect;

import com.tyq.greendao.HaveReadDao;
import com.tyq.greendao.CollectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig haveReadDaoConfig;
    private final DaoConfig collectDaoConfig;

    private final HaveReadDao haveReadDao;
    private final CollectDao collectDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        haveReadDaoConfig = daoConfigMap.get(HaveReadDao.class).clone();
        haveReadDaoConfig.initIdentityScope(type);

        collectDaoConfig = daoConfigMap.get(CollectDao.class).clone();
        collectDaoConfig.initIdentityScope(type);

        haveReadDao = new HaveReadDao(haveReadDaoConfig, this);
        collectDao = new CollectDao(collectDaoConfig, this);

        registerDao(HaveRead.class, haveReadDao);
        registerDao(Collect.class, collectDao);
    }
    
    public void clear() {
        haveReadDaoConfig.getIdentityScope().clear();
        collectDaoConfig.getIdentityScope().clear();
    }

    public HaveReadDao getHaveReadDao() {
        return haveReadDao;
    }

    public CollectDao getCollectDao() {
        return collectDao;
    }

}
