package com.tyq.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HAVE_READ.
 */
public class HaveRead {

    private Long id;
    private String title;
    private String imageUrl;
    private String url;

    public HaveRead() {
    }

    public HaveRead(Long id) {
        this.id = id;
    }

    public HaveRead(Long id, String title, String imageUrl, String url) {
        this.id = id;
        this.title = title;
        this.imageUrl = imageUrl;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
